application: bootstrap-block-editor
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# All my js and css at the moment
- url: /(.*)\.js
  static_files: \1.js
  upload: .*\.js

- url: /ink-2.2.0
  static_dir: ink-2.2.0

- url: /blockly
  static_dir: blockly

- url: /closure-library
  static_dir: closure-library

- url: /ray/blockly/.*\.html
  script: entry.application

- url: /editor/.*
  script: entry.application

- url: /programs/.*
  script: entry.application

- url: /ray
  static_dir: ray
  application_readable: true

- url: /
  script: entry.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: 2.6