* Dependencies:
** Less (> 1.3.1)
I use 'less', a superset of css that compiles to straight css in order
to make my css a lot simpler.  In order to make the css for the site,
run 

#+BEGIN_SRC sh
  make css
#+END_SRC

This requires the less compiler, 'lessc', which in
turns requires node.js.  Once 'node.js' is installed, less can be
installed globally by running 'npm install -g less'. This will install
lessc into your default global node_modules folder, which should be in
your $PATH. If it is, 'make css' should then work.

* How to get started:
** Ray
Ray is the top-level namespace for everything I've written. I chose
the name because it was short, matched the Marine Wildlife theme
established by Whalesong, and also was close to Racket.
** Application
You have to start up a server to run the application.  I'm just using
python's builtin HTTP server, so as long as you have some python
installation in your PATH, this should work.

You can do so with the following command:

#+BEGIN_SRC sh
  ./start-server
#+END_SRC

Run that from the root directory of the repository, and then navigate
to

http://localhost:8000/demo.html

to run the application.
** Tests
The test suite for Ray can be run and viewed by opening up
'ray/tests.html' in a web browser. No server is required.

If not using a server, you do need to provide the full path to the
file in order to view it in the browser.

If you'd like, you can run a server, with './start-server', and then
view the page at

http://localhost:8000/ray/tests.html


