// This file was autogenerated by closure-library-read-only/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../ray/jquery.js', ['ray.jquery'], []);
goog.addDependency('../../../ray/js-numbers.js', ['ray.js_numbers'], []);
goog.addDependency('../../../ray/kernel.js', ['ray.kernel'], ['ray.underscore', 'ray.util']);
goog.addDependency('../../../ray/lib.js', ['ray.lib'], ['ray.ray', 'ray.underscore']);
goog.addDependency('../../../ray/ray-numbers.js', ['ray.ray_numbers'], ['ray.js_numbers']);
goog.addDependency('../../../ray/ray.js', ['ray.ray'], ['ray.kernel', 'ray.ray_numbers']);
goog.addDependency('../../../ray/test.js', ['ray.test'], ['ray.jquery', 'ray.lib', 'ray.ray', 'ray.underscore']);
goog.addDependency('../../../ray/underscore.js', ['ray.underscore'], []);
goog.addDependency('../../../ray/util.js', ['ray.util'], ['ray.underscore']);
